version: '3.8'

services:
    mysql.5.7:
        image: mysql:5.7
        container_name: mysql.5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql:/tmp/database
        command: mysqld --init-file="/tmp/database/init.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_DATABASE=redmine
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.5

networks:
    bridge.66.6:
        ipam:
            driver: default
            config:
                - subnet: "66.6.0.0/16"
volumes:
    mysql.5.7: