version: '3'

services:
    integrator:
        image: wso2/wso2ei-integrator
        container_name: integrator
        ports:
            - "8280:8280"
            - "8243:8243"
            - "9443:9443"

    # analytics-dashboard:
    #     image: wso2/wso2ei-analytics-dashboard
    #     container_name: analytics-dashboard
    #     ports:
    #         - "9713:9713"
    #         - "9643:9643"
    #         - "9613:9613"
    #         - "7713:7713"
    #         - "7613:7613"
    
    # analytics-worker:
    #     image: wso2/wso2ei-analytics-worker
    #     container_name: analytics-worker
    #     ports:
    #         - "9091:9091"
    #         - "9444:9444"
    #         - "9712:9712"
    #         - "9612:9612"
    #         - "7712:7712"
    #         - "7612:7612"
    #         - "7070:7070"
    #         - "7443:7443"

    # analytics-worker:
    #     image: wso2/wso2ei-analytics-worker
    #     container_name: analytics-worker
    #     ports:
    #         - "9091:9091"
    #         - "9444:9444"
    #         - "9712:9712"
    #         - "9612:9612"
    #         - "7712:7712"
    #         - "7612:7612"
    #         - "7070:7070"
    #         - "7443:7443"