version: '3'

services:
    php:
        image: php:7.1.26-apache
        container_name: php
        ports:
            - "80:80"
        volumes: 
            - ./app01:/var/www/html
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.10

networks:
    bridge.66.6:
        ipam:
            driver: default
            config:
                - subnet: "66.6.0.0/16"