version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - 'mariadb:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_unicode_ci
    networks:
      - bd
  moodle:
    build:
      context: ./moodle
      dockerfile: Dockerfile
      args:
        - EXTRA_LOCALES=pt_BR.UTF-8
    container_name: moodle
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'moodle:/bitnami/moodle'
      - 'moodledata:/bitnami/moodledata'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin
      - MOODLE_SITE_NAME=Docker
    networks:
      - bd
    depends_on:
      - mariadb
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000"
      - "7000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - bd
networks:
    bd:
volumes:
    mariadb:
    moodle:
    moodledata:
    portainer_data: