# Use tech_user/secret as user/password credentials
version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: example
    command:
      - -c
      - max_prepared_transactions=100
    networks:
        - backend

  bonita:
    image: bonita
    ports:
      - 8080:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD=example
      - DB_VENDOR=postgres
      - DB_HOST=db
      - TENANT_LOGIN=tech_user
      - TENANT_PASSWORD=secret
      - PLATFORM_LOGIN=pfadmin
      - PLATFORM_PASSWORD=pfsecret
    depends_on:
      - db
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh
    networks:
        - backend

  portainer:
      image: portainer/portainer-ce
      container_name: portainer
      ports:
          - "8000:8000"
          - "7000:9000"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
      networks:
          - backend

networks:
    backend:

volumes:
    portainer_data: