version: '3'

services:
    mysql.5.7:
        image: mysql:5.7
        container_name: mysql.5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql:/tmp/database
        command: mysqld --init-file="/tmp/database/init.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_PASSWORD=my-password
            - MYSQL_DATABASE=tecnocrata_org
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.5
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports: 
            - "8080:80"
        environment:
            - PMA_HOST=mysql.5.7
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.10
        depends_on:
            - mysql.5.7
networks:
    bridge.66.6:
        ipam:
            driver: default
            config:
                - subnet: "66.6.0.0/24"

volumes:
    mysql.5.7: