version: '3.8'

services:
    mysql.5.7:
        build:
            context: './mysql/'
            dockerfile: 'Dockerfile'
            args:
                buildno: 1
            labels: 
                description: "mysqlmysql"
        container_name: mysql.5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql/sql-scripts:/tmp/database
        command: mysqld --init-file="/tmp/database/redmine.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_DATABASE=redmine
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.5
    redmine:
        build: 
            context: './redmine/'
            dockerfile: 'Dockerfile'
            args:
                buildno: 1
            labels: 
                description: "redred"
        container_name: redmine
        ports:
            - "80:3000"
        env_file: .env
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.10
        depends_on:
            - mysql.5.7

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - "8081:80"
        environment:
            - PMA_HOST=mysql.5.7
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.4
        depends_on:
            - mysql.5.7

networks:
    bridge.66.6:
        ipam:
            driver: default
            config:
                - subnet: "66.6.0.0/16"
volumes:
    mysql.5.7: