version: "3.4"

services:
    app:
      image: monica
      depends_on:
        - db
      ports:
        - 8080:80
      environment:
        - APP_KEY=iuhjygasdjyghuioihdaysdkjkfjhfhg
        - DB_HOST=db
        - DB_USERNAME=monica
        - DB_PASSWORD=secret
      volumes:
        - app_data:/var/www/html/storage

    db:
      image: mysql:5.7
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=true
        - MYSQL_DATABASE=monica
        - MYSQL_USER=monica
        - MYSQL_PASSWORD=secret
      volumes:
        - monica_mysql:/var/lib/mysql

    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "8000:8000"
            - "7000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - backend

networks:
    backend:

volumes:
    portainer_data:
    app_data:
      name: app_datadata
    monica_mysql:
      name: monica_mysql