version: '3.8'

services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend
            
    express:
        image: express-gateway
        container_name: express
        ports:
            - "8080:8080"
            - "9876:9876"
        volumes:
            - /my/own/datadir:/var/lib/eg
        networks:
            - backend
        
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "8000:8000"
            - "7000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - backend

networks:
    backend:

volumes:
    portainer_data: