version: '3.8'

services:
    mysql.5.7:
        image: mysql:5.7
        container_name: mysql.5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql:/tmp/database
        command: mysqld --init-file="/tmp/database/init.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_DATABASE=redmine

    redmine:
        image: redmine
        container_name: redmine
        ports:
            - "80:3000"
        env_file: .env
        depends_on:
            - mysql.5.7

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - "8080:80"
        environment:
            - PMA_HOST=mysql.5.7
        depends_on:
            - mysql.5.7

volumes:
    mysql.5.7: