version: '3.8'

services:
    centos8:
        build:
            context: './centos8/'
            dockerfile: 'Dockerfile'
            args:
                buildno: 1
            labels: 
                description: "centos8centos8"
        container_name: centos8

       