version: '3.8'

services:
    mysql.5.7:
        image: mysql:5.7
        container_name: mysql.5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql:/tmp/database
        command: mysqld --init-file="/tmp/database/init.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_DATABASE=tecnocrata_org
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.5
    php:
        build: 
            context: './php/'
            dockerfile: 'Dockerfile'
            args:
                buildno: 1
            labels: 
                description: "phhh"
        container_name: php
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./app01/:/var/www/html/
        env_file: .env
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.10
        depends_on:
            - mysql.5.7

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - "8081:80"
        restart: always
        environment:
            - PMA_HOST=mysql.5.7
        networks:
            bridge.66.6:
                ipv4_address: 66.6.0.4
        depends_on:
            - mysql.5.7

networks:
    bridge.66.6:
        ipam:
            driver: default
            config:
                - subnet: "66.6.0.0/16"
volumes:
    mysql.5.7: