version: '3'

services:
    mysql.5.7:
        image: mysql:5.7
        container_name: mysql.5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql.5.7:/var/lib/mysql
            - ./mysql:/tmp/database
        command: mysqld --init-file="/tmp/database/init.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=my-password
            - MYSQL_DATABASE=tecnocrata_org
        networks:
            - bd
    php:
        image: php:7-fpm-buster
        container_name: php
        restart: always
        volumes:
            - ../src:/var/www
            - ".:/var/www/html"
            - "./php/php.ini:/usr/local/etc/php/php.ini"
        command:
            - /bin/sh
            - -c
            - |
                docker-php-ext-install mysqli pdo pdo_mysql pdo_pgsql
                echo "extension installed.....starting php-fpm........................................"
                php-fpm
        networks:
            - bd
        depends_on:
            - mysql.5.7
    nginx:
        container_name: nginx
        restart: always
        ports:
            - "8027:80"
            - "443:443"
        build:
            context: ./nginx
        volumes:
            - ../src:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php
        networks:
            - bd
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports: 
            - "8080:80"
        environment:
            - PMA_HOST=mysql.5.7
        networks:
            - bd
        depends_on:
            - mysql.5.7
networks:
    bd:

volumes:
    mysql.5.7: