version: "3.7"

services:
    caddy:
        image: caddy
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - $PWD/Caddyfile:/etc/caddy/Caddyfile
          - $PWD/site:/srv
          - caddy_data:/data
          - caddy_config:/config
        networks:
            - backend


    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - "8000:8000"
            - "7000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - backend

networks:
    backend:

volumes:
  caddy_data:
  caddy_config:
  portainer_data: